### PR TITLE
Re-calculate keyboard height in view

### PR DESCRIPTION
**Pull request by duc-ios**

### CODE REVIEW

**Comment by podkovyrin** [comment]
This doesn't make any sense because when keyboard `UIKeyboardWillShowNotification` received you should get keyboard height from it, according to documentation https://developer.apple.com/library/ios/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/KeyboardManagement/KeyboardManagement.html#//apple_ref/doc/uid/TP40009542-CH5-SW3

Did you have any issues with original code?

**Comment by duc-ios** [comment]
I met an issue when using Keyboardy in a container view where view height is smaller than the window height.

https://i.imgur.com/25ekLRK.png
Let's say:
- Orange line is the window frame.
- Blue line is my container view.
- Green line is the keyboard frame.

-> If using the original keyboard height for a bottom constrain in my container view, I will have a space between the keyboard and my view bottom.

**Comment by podkovyrin** [comment]
It seems, that you should manage keyboard from your parent container controller, instead of child and than propagate this updates to child controller if necessary.

**Comment by duc-ios** [comment]
This is also happened with ViewControllers inside opaque TabBarController.

**Comment by podkovyrin** [comment]
Could you provide a sample project with this issue?

**Comment by duc-ios** [comment]
Yes, sure, checkout my project:
https://github.com/masd-duc/Keyboardy-PR1

**Pull request closed without merging**
